polygon_pos_package:
  network_params:
    el_block_interval_seconds: 1

  participants:
    # 5 validators on Bor's stateless_sync branch
    - kind: validator
      cl_type: heimdall-v2
      cl_image: heimdall-v2:local
      el_type: bor
      el_image: bor:local
      count: 5
      el_bor_produce_witness: true
      el_log_level: info

    # 3 validators using stateless sync. Any of them having sync issue will cause the test to fail.
    - kind: validator
      cl_type: heimdall-v2
      cl_image: heimdall-v2:local
      el_type: bor
      el_image: bor:local
      count: 3
      el_bor_produce_witness: true
      el_log_level: info
      el_bor_sync_mode: stateless

    # 1 validator with Bor 2.2.9
    - kind: validator
      cl_type: heimdall-v2
      cl_image: heimdall-v2:local
      el_type: bor
      el_image: 0xpolygon/bor:2.2.9
      count: 1
      el_bor_produce_witness: false
      el_bor_sync_with_witness: false

    # 3 Total RPC nodes on Bor's stateless_sync branch
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: heimdall-v2:local
      el_type: bor
      el_image: bor:local
      count: 1
      el_bor_produce_witness: false
      el_bor_sync_with_witness: false

    - kind: rpc
      cl_type: heimdall-v2
      cl_image: heimdall-v2:local
      el_type: bor
      el_image: bor:local
      count: 1
      el_bor_produce_witness: true
      el_bor_sync_with_witness: false

    - kind: rpc
      cl_type: heimdall-v2
      cl_image: heimdall-v2:local
      el_type: bor
      el_image: bor:local
      count: 1
      el_bor_produce_witness: true
      el_bor_sync_with_witness: true

  additional_services:
    - prometheus_grafana
    - test_runner
